name: Hideme
version: ${project.version}
main: me.mohamedelyousfi.hideme.Hideme
api-version: 1.16.1
authors: [mohagames]
description: Hide yourself like never before
website: mohamedelyousfi.me

commands:
  vanish:
    description: Verberg jezelf van de andere spelers
    permission: hideme.vanish

permissions:
  hideme.bypass:
    default: op
    description: Deze permission zorgt ervoor dat je gevanishde spelers kan zien
  hideme.vanish:
    default: op
    description: Permission om de vanish command te gebruiken